### Sign in and get access token
POST {{supabaseUrl}}/auth/v1/token?grant_type=password
apikey: {{supabaseAnonKey}}
Content-Type: application/json

{
  "email": "{{testEmail}}",
  "password": "{{testPassword}}"
}

> {%
    client.global.set("authToken", response.body.access_token);
    client.global.set("userId", response.body.user.id);
    client.log("Access token saved: " + response.body.access_token);
    client.log("User ID saved: " + response.body.user.id);
%}

### Get all lists
GET {{supabaseUrl}}/rest/v1/lists
apikey: {{supabaseAnonKey}}
Authorization: Bearer {{authToken}}

### Create a new list
POST {{supabaseUrl}}/rest/v1/lists
apikey: {{supabaseAnonKey}}
Authorization: Bearer {{authToken}}
Content-Type: application/json
Prefer: return=representation

{
  "name": "My Wishlist",
  "created_by": "{{userId}}"
}

> {%
    client.global.set("listId", response.body[0].id);
    client.log("Created list ID: " + response.body[0].id);
%}

### Get lists for current user only
GET {{supabaseUrl}}/rest/v1/lists?created_by=eq.{{userId}}
apikey: {{supabaseAnonKey}}
Authorization: Bearer {{authToken}}

### Delete a specific list (using saved listId)
DELETE {{supabaseUrl}}/rest/v1/lists?id=eq.{{listId}}
apikey: {{supabaseAnonKey}}
Authorization: Bearer {{authToken}}